---
- name: Ensure SELinux is disabled
  ansible.posix.selinux:
    state: disabled
  register: selinux_result
  notify:
    - Reboot system if SELinux status changed
    
- name: Ensure firewalld is enabled and running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
    
- name: Open port 80/tcp in firewalld
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true
  notify:
    - Reload firewalld
    
- name: Reboot system if SELinux status changed
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to SELinux status change."
    reboot_timeout: 600
  when: reboot_required
  
- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
